services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
  #   depends_on:
  #     - db
  # db:
  #   image: mysql
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PASSWORD=
  #     - MYSQL_DATABASE=node_js_crud
